// FILE: lib/services/subject_vocabulary.dart
class SubjectVocabulary {
  // Weighted vocabulary for subject detection
  // Score: 1 (common) to 5 (highly specific)
  static final Map<String, Map<String, int>> vocabulary = {
    'Mathematics': {
      'calculation': 2,
      'equation': 4,
      'number': 1,
      'theorem': 5,
      'algebra': 5,
      'geometry': 5,
      'fraction': 3,
      'sum': 1,
      'angle': 3,
      'graph': 2,
      'multiply': 2,
      'divide': 2,
      'subtract': 2,
      'addition': 2,
      'percentage': 3,
      'ratio': 3,
      'variable': 3,
      'function': 4,
      'derivative': 5,
      'integral': 5,
      'matrix': 4,
      'probability': 4,
      'statistics': 4,
      'coordinate': 3,
      'polygon': 4,
      'triangle': 2,
      'circle': 2,
      'volume': 3,
      'area': 2,
      'perimeter': 3,
      'proof': 3,
      'axiom': 5,
      'calculus': 5,
      'trigonometry': 5,
      'arithmetic': 4,
      'linear': 3,
      'vector': 4,
      'scalar': 3,
      'polynomial': 4,
      'logarithm': 4,
      'exponential': 3,
      'limit': 3,
      'series': 3,
      'sequence': 3,
    },
    'Physics': {
      'gravity': 5,
      'force': 4,
      'energy': 3,
      'velocity': 4,
      'acceleration': 4,
      'motion': 3,
      'mass': 3,
      'friction': 4,
      'momentum': 5,
      'inertia': 5,
      'torque': 5,
      'thermodynamics': 5,
      'quantum': 5,
      'relativity': 5,
      'optics': 4,
      'magnetism': 4,
      'electricity': 4,
      'circuit': 3,
      'voltage': 4,
      'current': 3,
      'resistance': 3,
      'wave': 3,
      'frequency': 3,
      'amplitude': 4,
      'particle': 3,
      'atom': 3,
      'nucleus': 4,
      'radiation': 4,
      'spectrum': 4,
      'lens': 3,
      'mirror': 2,
      'refraction': 5,
    },
    'Chemistry': {
      'chemical': 4,
      'reaction': 4,
      'molecule': 4,
      'atom': 3,
      'element': 4,
      'compound': 4,
      'periodic': 5,
      'table': 2,
      'acid': 4,
      'base': 3,
      'ph': 5,
      'solution': 3,
      'mixture': 3,
      'bond': 3,
      'covalent': 5,
      'ionic': 5,
      'organic': 4,
      'inorganic': 4,
      'catalyst': 5,
      'enzyme': 4,
      'oxidation': 5,
      'reduction': 5,
      'mole': 4,
      'stoichiometry': 5,
      'gas': 2,
      'liquid': 2,
      'solid': 2,
      'plasma': 4,
      'polymer': 4,
      'synthesis': 4,
      'analysis': 2,
      'laboratory': 3,
    },
    'Biology': {
      'cell': 5,
      'dna': 5,
      'rna': 5,
      'gene': 5,
      'protein': 4,
      'enzyme': 4,
      'organism': 4,
      'species': 4,
      'evolution': 5,
      'ecology': 4,
      'ecosystem': 4,
      'photosynthesis': 5,
      'respiration': 4,
      'metabolism': 5,
      'anatomy': 4,
      'physiology': 4,
      'bacteria': 4,
      'virus': 4,
      'fungi': 4,
      'plant': 2,
      'animal': 2,
      'human': 2,
      'brain': 3,
      'heart': 3,
      'tissue': 3,
      'organ': 3,
      'system': 2,
      'reproduction': 4,
      'genetics': 5,
      'inheritance': 4,
      'mutation': 4,
      'adaptation': 4,
    },
    'History': {
      'century': 2,
      'war': 3,
      'empire': 4,
      'ancient': 3,
      'revolution': 4,
      'king': 2,
      'queen': 2,
      'civilization': 4,
      'timeline': 3,
      'historical': 2,
      'monarchy': 4,
      'democracy': 3,
      'battle': 3,
      'treaty': 4,
      'independence': 3,
      'colony': 4,
      'dynasty': 5,
      'archaeology': 4,
      'artifact': 4,
      'culture': 2,
      'tradition': 2,
      'rebellion': 3,
      'constitution': 4,
      'parliament': 4,
      'president': 3,
      'dictator': 4,
      'conquest': 4,
      'migration': 3,
      'slavery': 4,
      'feudalism': 5,
      'renaissance': 5,
      'industrial': 3,
      'medieval': 4,
      'prehistoric': 4,
      'archaeologist': 5,
      'historian': 4,
    },
    'Literature': {
      'story': 2,
      'character': 3,
      'novel': 4,
      'poem': 4,
      'author': 3,
      'narrative': 4,
      'plot': 3,
      'theme': 3,
      'fiction': 3,
      'drama': 4,
      'prose': 5,
      'metaphor': 5,
      'simile': 4,
      'imagery': 4,
      'symbolism': 4,
      'dialogue': 3,
      'protagonist': 5,
      'antagonist': 5,
      'climax': 4,
      'resolution': 3,
      'genre': 3,
      'biography': 4,
      'autobiography': 4,
      'essay': 3,
      'rhyme': 3,
      'stanza': 4,
      'verse': 3,
      'literature': 5,
      'reading': 1,
      'writing': 1,
      'chapter': 2,
      'book': 1,
      'sonnet': 5,
      'haiku': 5,
      'epic': 4,
      'tragedy': 4,
      'comedy': 3,
    },
    'Geography': {
      'map': 3,
      'region': 2,
      'climate': 4,
      'population': 3,
      'mountain': 2,
      'river': 2,
      'country': 2,
      'continent': 4,
      'landscape': 3,
      'environment': 3,
      'latitude': 5,
      'longitude': 5,
      'equator': 5,
      'hemisphere': 4,
      'ocean': 2,
      'desert': 3,
      'forest': 2,
      'plateau': 4,
      'valley': 3,
      'volcano': 4,
      'earthquake': 4,
      'weather': 2,
      'atmosphere': 3,
      'resources': 2,
      'agriculture': 3,
      'urban': 3,
      'rural': 3,
      'migration': 3,
      'capital': 2,
      'border': 2,
      'terrain': 3,
      'glacier': 4,
      'topography': 5,
      'cartography': 5,
      'demographics': 5,
      'geology': 4,
    },
    'Computer Science': {
      'computer': 2,
      'code': 3,
      'algorithm': 5,
      'data': 2,
      'network': 3,
      'software': 4,
      'hardware': 4,
      'internet': 3,
      'programming': 4,
      'digital': 2,
      'database': 4,
      'server': 4,
      'cloud': 3,
      'security': 3,
      'encryption': 5,
      'variable': 3,
      'loop': 3,
      'function': 3,
      'class': 2,
      'object': 2,
      'interface': 3,
      'input': 2,
      'output': 2,
      'processor': 4,
      'memory': 3,
      'storage': 3,
      'binary': 4,
      'pixel': 3,
      'browser': 3,
      'application': 3,
      'developer': 3,
      'bug': 2,
      'api': 4,
      'framework': 4,
      'compiler': 5,
      'debugging': 4,
      'artificial': 3,
      'intelligence': 3,
      'machine': 2,
      'learning': 2,
    },
    'Economics': {
      'economy': 5,
      'market': 3,
      'supply': 4,
      'demand': 4,
      'price': 2,
      'cost': 2,
      'inflation': 5,
      'deflation': 5,
      'gdp': 5,
      'tax': 3,
      'budget': 3,
      'finance': 4,
      'investment': 4,
      'capital': 3,
      'labor': 3,
      'trade': 3,
      'export': 4,
      'import': 4,
      'currency': 4,
      'bank': 3,
      'interest': 3,
      'rate': 2,
      'monopoly': 5,
      'competition': 3,
      'consumer': 3,
      'producer': 3,
      'revenue': 4,
      'profit': 3,
    },
    'Political Science': {
      'government': 4,
      'politics': 5,
      'policy': 4,
      'law': 3,
      'rights': 3,
      'justice': 3,
      'state': 2,
      'nation': 3,
      'democracy': 4,
      'republic': 4,
      'election': 4,
      'vote': 3,
      'campaign': 3,
      'party': 3,
      'candidate': 3,
      'citizen': 3,
      'constitution': 5,
      'amendment': 5,
      'legislature': 5,
      'executive': 5,
      'judicial': 5,
      'court': 3,
      'judge': 3,
      'diplomacy': 5,
      'international': 3,
      'relations': 2,
      'power': 2,
      'authority': 4,
    },
    'Psychology': {
      'mind': 4,
      'behavior': 4,
      'brain': 3,
      'cognitive': 5,
      'emotion': 4,
      'memory': 3,
      'perception': 4,
      'consciousness': 5,
      'development': 3,
      'personality': 4,
      'disorder': 4,
      'therapy': 4,
      'mental': 3,
      'health': 2,
      'stress': 3,
      'anxiety': 4,
      'depression': 4,
      'social': 2,
      'interaction': 3,
      'group': 2,
      'neuron': 4,
      'synapse': 5,
      'learning': 2,
      'conditioning': 5,
    },
  };

  // Common interchangeable words that might appear in multiple subjects
  // These should be disambiguated based on context
  static final Set<String> ambiguousTerms = {
    'variable',
    'function',
    'class',
    'table',
    'volume',
    'power',
    'force',
    'energy',
    'solution',
    'root',
    'base',
    'factor',
    'degree',
    'scale',
    'period',
    'operation',
    'element',
  };

  // Get score for a term in a specific subject
  static int getTermScore(String term, String subject) {
    return vocabulary[subject]?[term] ?? 0;
  }
}
